# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "load_data": "train_2.ipynb",
         "tokenize": "train_2.ipynb",
         "build_model": "train_2.ipynb",
         "evaluate_model": "train_2.ipynb",
         "save_model": "train_2.ipynb",
         "main": "train_2.ipynb"}

modules = ["core.py",
           "train_2.py"]

doc_url = "https://duyminh2420.github.io/disaster_repository_lib/"

git_url = "https://github.com/duyminh2420/disaster_repository_lib/tree/master/"

def custom_doc_links(name): return None
